# Generated by Django 4.2.3 on 2024-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (4, 'ORDER_REJECTED'), (3, 'ORDER_DELIVERED'), (1, 'ORDER_CONFIRMED')], default=0),
        ),
    ]
